# Generated by Django 3.1.5 on 2021-01-27 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Slider', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Slider',
            new_name='Slider2',
        ),
    ]
