# Generated by Django 2.2.10 on 2021-01-30 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProjectName', models.CharField(max_length=250)),
                ('Permalink', models.CharField(max_length=250)),
                ('ProjectTitle', models.CharField(max_length=250)),
                ('BrowserTitle', models.CharField(max_length=250)),
                ('MetaKeyword', models.TextField(null=True)),
                ('MetaDescription', models.TextField(null=True)),
                ('CategoryName', models.TextField(null=True)),
                ('LiveUrl', models.CharField(max_length=250, null=True)),
                ('SliderImage', models.ImageField(upload_to='portfolio/')),
                ('ImageTitleText', models.CharField(max_length=250, null=True)),
                ('ImageAltText', models.CharField(max_length=250, null=True)),
                ('ProjectDetails', models.TextField(null=True)),
                ('ActiveStatus', models.IntegerField(default='0')),
            ],
        ),
        migrations.CreateModel(
            name='portfolioCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(max_length=250)),
                ('Permalink', models.CharField(max_length=250)),
                ('MetaKeyword', models.TextField(max_length=250)),
                ('MetaDescription', models.TextField(max_length=250)),
                ('BrowserTitle', models.TextField(max_length=250)),
            ],
        ),
    ]
