# Generated by Django 2.2.10 on 2021-01-30 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0003_remove_portfolio_categoryname'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='CategoryName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Portfolio.portfolioCategory'),
        ),
    ]
