# Generated by Django 3.1.5 on 2021-01-25 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Person2',
        ),
    ]
