# Generated by Django 3.1.5 on 2021-01-25 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20210125_1922'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person2',
            new_name='Person',
        ),
    ]
