# Generated by Django 3.1.5 on 2021-01-27 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_slider'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slider',
        ),
    ]
